// <auto-generated />
using System;
using EcoRoute.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoRoute.Migrations
{
    [DbContext(typeof(EcoRouteDbContext))]
    [Migration("20251210172236_AddedNotificationTable")]
    partial class AddedNotificationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoRoute.Models.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("'COMP-' + CAST(Id AS NVARCHAR(20))", true);

                    b.Property<DateTime>("CompanyCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CompanyCredits")
                        .HasColumnType("float");

                    b.Property<double>("CompanyEmissionBudget")
                        .HasColumnType("float");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanySector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("EcoRoute.Models.Entities.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CreditMarketPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("LatestDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("EcoRoute.Models.Entities.CreditListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuyerCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CreditsListed")
                        .HasColumnType("float");

                    b.Property<DateTime>("ListedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("PricePerCredit")
                        .HasColumnType("float");

                    b.Property<int>("SellerCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CreditListings");
                });

            modelBuilder.Entity("EcoRoute.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRefrigerated")
                        .HasColumnType("bit");

                    b.Property<double>("OrderCO2Emission")
                        .HasColumnType("float");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("'ODR-' + CAST(Id AS NVARCHAR(20))", true);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderDestination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderDistance")
                        .HasColumnType("float");

                    b.Property<double>("OrderHeight")
                        .HasColumnType("float");

                    b.Property<double>("OrderLength")
                        .HasColumnType("float");

                    b.Property<string>("OrderMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderStandardCO2Emissions")
                        .HasColumnType("float");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderTotalItems")
                        .HasColumnType("int");

                    b.Property<double>("OrderWeightKg")
                        .HasColumnType("float");

                    b.Property<double>("OrderWidth")
                        .HasColumnType("float");

                    b.Property<string>("SelectedPolyline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedRouteSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<string>("TransportMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EcoRoute.Models.Entities.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ShipmentCO2Emission")
                        .HasColumnType("float");

                    b.Property<string>("ShipmentCode")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("'SHIP-' + CAST(Id AS NVARCHAR(20))", true);

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipmentDestination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ShipmentDistance")
                        .HasColumnType("float");

                    b.Property<double>("ShipmentHeight")
                        .HasColumnType("float");

                    b.Property<double>("ShipmentLength")
                        .HasColumnType("float");

                    b.Property<string>("ShipmentOrgin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipmentTotalItems")
                        .HasColumnType("int");

                    b.Property<double>("ShipmentWeightKg")
                        .HasColumnType("float");

                    b.Property<double>("ShipmentWidth")
                        .HasColumnType("float");

                    b.Property<string>("Vehicle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("EcoRoute.Models.Entities.TruckType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CargoHeightMeters")
                        .HasColumnType("float");

                    b.Property<double>("CargoLengthMeters")
                        .HasColumnType("float");

                    b.Property<double>("CargoWidthMeters")
                        .HasColumnType("float");

                    b.Property<double>("DragCoefficient")
                        .HasColumnType("float");

                    b.Property<double>("EngineEfficiency")
                        .HasColumnType("float");

                    b.Property<double>("GVWKg")
                        .HasColumnType("float");

                    b.Property<double>("KerbWeight")
                        .HasColumnType("float");

                    b.Property<double>("MaxPayloadKg")
                        .HasColumnType("float");

                    b.Property<string>("TruckName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TruckTypes");
                });

            modelBuilder.Entity("EcoRoute.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcoRoute.Models.HelperClasses.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetCompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TargetCompanyId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EcoRoute.Models.Entities.Order", b =>
                {
                    b.HasOne("EcoRoute.Models.Entities.Company", "Company")
                        .WithMany("OrderList")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoRoute.Models.Entities.Shipment", "Shipment")
                        .WithMany("OrderList")
                        .HasForeignKey("ShipmentId");

                    b.Navigation("Company");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("EcoRoute.Models.HelperClasses.Notification", b =>
                {
                    b.HasOne("EcoRoute.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("TargetCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EcoRoute.Models.Entities.Company", b =>
                {
                    b.Navigation("OrderList");
                });

            modelBuilder.Entity("EcoRoute.Models.Entities.Shipment", b =>
                {
                    b.Navigation("OrderList");
                });
#pragma warning restore 612, 618
        }
    }
}
